from __future__ import annotations

from PySide6 import QtCore, QtWidgets


class DisplaySettingsDialog(QtWidgets.QDialog):
    def __init__(self, font_size: int, curve_scale: float, parent=None) -> None:
        super().__init__(parent)
        self.setObjectName("displaySettingsDialog")
        self.setProperty("uiRole", "dialog")
        self.setWindowTitle("显示设置")
        self.setModal(True)
        self.resize(500, 340)
        self.setMinimumSize(420, 300)
        self.setSizeGripEnabled(True)

        layout = QtWidgets.QVBoxLayout(self)
        layout.setContentsMargins(16, 16, 16, 16)
        layout.setSpacing(12)

        header = QtWidgets.QHBoxLayout()
        header.setSpacing(12)
        title_stack = QtWidgets.QVBoxLayout()
        title_stack.setSpacing(2)
        title = QtWidgets.QLabel("显示设置")
        title.setObjectName("dialogTitle")
        title.setProperty("uiRole", "screenTitle")
        subtitle = QtWidgets.QLabel("匹配屏幕尺寸与操作距离")
        subtitle.setObjectName("subtitle")
        subtitle.setProperty("uiRole", "secondaryText")
        title_stack.addWidget(title)
        title_stack.addWidget(subtitle)
        header.addLayout(title_stack)
        header.addStretch()
        badge = QtWidgets.QLabel("原：DisplaySettingsDialog")
        badge.setObjectName("originBadge")
        badge.setProperty("uiRole", "originBadge")
        header.addWidget(badge, alignment=QtCore.Qt.AlignmentFlag.AlignTop)
        layout.addLayout(header)

        intro = QtWidgets.QLabel("调整全界面字体与曲线高度，便于不同屏幕和观看距离使用。")
        intro.setObjectName("hintPanel")
        intro.setProperty("uiRole", "hintPanel")
        intro.setWordWrap(True)
        layout.addWidget(intro)

        card = QtWidgets.QGroupBox("界面比例")
        card.setObjectName("formCard")
        card.setProperty("uiRole", "formPanel")
        form = QtWidgets.QFormLayout(card)
        form.setContentsMargins(12, 16, 12, 12)
        form.setHorizontalSpacing(16)
        form.setVerticalSpacing(12)
        form.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldGrowthPolicy.AllNonFixedFieldsGrow)

        card_badge = QtWidgets.QLabel("原：DisplaySettingsDialog")
        card_badge.setObjectName("panelBadge")
        card_badge.setProperty("uiRole", "panelBadge")
        form.addRow(card_badge)

        self.font_spin = QtWidgets.QSpinBox()
        self.font_spin.setObjectName("fontSizeSpin")
        self.font_spin.setProperty("uiRole", "numericField")
        self.font_spin.setRange(10, 22)
        self.font_spin.setSuffix(" pt")
        self.font_spin.setValue(font_size)
        self.font_spin.setAccessibleName("界面字体大小")
        self.scale_combo = QtWidgets.QComboBox()
        self.scale_combo.setObjectName("curveScaleCombo")
        self.scale_combo.setProperty("uiRole", "formField")
        self.scale_combo.addItem("紧凑", 0.8)
        self.scale_combo.addItem("标准", 1.0)
        self.scale_combo.addItem("宽松", 1.2)
        self.scale_combo.addItem("大曲线", 1.4)
        index = min(range(self.scale_combo.count()), key=lambda i: abs(float(self.scale_combo.itemData(i)) - curve_scale))
        self.scale_combo.setCurrentIndex(index)

        font_label = QtWidgets.QLabel("界面字体")
        font_label.setObjectName("fieldLabel")
        font_label.setProperty("uiRole", "fieldLabel")
        font_label.setBuddy(self.font_spin)
        scale_label = QtWidgets.QLabel("曲线高度")
        scale_label.setObjectName("fieldLabel")
        scale_label.setProperty("uiRole", "fieldLabel")
        scale_label.setBuddy(self.scale_combo)
        form.addRow(font_label, self.font_spin)
        form.addRow(scale_label, self.scale_combo)
        layout.addWidget(card)
        layout.addStretch()

        buttons = QtWidgets.QDialogButtonBox(QtWidgets.QDialogButtonBox.StandardButton.Ok | QtWidgets.QDialogButtonBox.StandardButton.Cancel)
        buttons.setObjectName("dialogButtons")
        buttons.setProperty("uiRole", "dialogActions")
        ok_button = buttons.button(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        cancel_button = buttons.button(QtWidgets.QDialogButtonBox.StandardButton.Cancel)
        ok_button.setText("确定")
        ok_button.setObjectName("primaryButton")
        ok_button.setProperty("uiRole", "primaryButton")
        ok_button.setDefault(True)
        cancel_button.setText("取消")
        buttons.accepted.connect(self.accept)
        buttons.rejected.connect(self.reject)
        layout.addWidget(buttons)

        QtWidgets.QWidget.setTabOrder(self.font_spin, self.scale_combo)
        QtWidgets.QWidget.setTabOrder(self.scale_combo, cancel_button)
        QtWidgets.QWidget.setTabOrder(cancel_button, ok_button)

    def values(self) -> tuple[int, float]:
        return self.font_spin.value(), float(self.scale_combo.currentData())
